# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eecba3dc38e8351f32c57d08411a2b0eba6f1d131ed91e1be545e83ccb07b0ed3e5970a7c8bb257793c3efe150dbf0d2cfc1d6fc0b851edea063f50c65062aa3

test:
  secret_key_base: 97cb62d002f82e285214898e78709146604a29a2d8212e75167b78fe37a724a50b69b59e87d2482c80eab2f0a1208760dfe12d8774c0e377eaeafd05c2740d7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
